- hosts: bootnodes
  gather_facts: yes
  become: yes
  vars:
    install: true
  environment:
    HTTP_PROXY: http://proxy.example.com:8080
    HTTPS_PROXY: http://proxy.example.com:8080
    NO_PROXY: localhost,127.,10.,192.168.
    http_proxy: http://proxy.example.com:8080
    https_proxy: http://proxy.example.com:8080
    no_proxy: localhost,127.,10.,192.168.
  roles:
    - lacchain-bootnode
