---
- name: Init pantheon
  debug:
    msg: "Init Pantheon"

- name: create lacchain directories
  file:
    path: "{{ item.dest }}"
    mode: "{{ item.mode }}"
    state: directory
  with_items:
    - { dest: "~/lacchain/data/keystore", mode: "0440" }
    - { dest: "~/lacchain/logs", mode: "0440" }
    - { dest: "~/lacchain/tmp", mode: "0440" }

- name: initializing pantheon from genesis.json
  debug:
    msg: Initializing Pantheon

- name: Copy genesis ibft2.0 file
  copy:
    src: "{{ role_path }}/files/genesis.json"
    dest: ~/lacchain/data/genesis.json
    mode: 0755

- name: Copy node key to first validator node
  copy:
    src: "{{ role_path }}/files/key"
    dest: ~/lacchain/data/key
    mode: 0700
  when: first_node

- name: Generate node key
  shell: pantheon --data-path=/root/lacchain/data public-key export-address --to=/root/lacchain/data/nodeAddress | grep -oE "0x[A-Fa-f0-9]*" | sed 's/0x//'
  register: enode_key

- name: print enode key
  debug:
    msg: enode://{{enode_key.stdout}}@{{node_ip}}:60606

- name: copy address to first validator node
  copy:
    src: "{{ role_path }}/files/UTC--2017-09-20T08-43-59.003454005Z--58b8527743f89389b754c63489262fdfc9ba9db6"
    dest: ~/lacchain/data/keystore/UTC--2017-09-20T08-43-59.003454005Z--58b8527743f89389b754c63489262fdfc9ba9db6
    mode: 0700
  when: first_node

- name: Generate shell script to execute pantheon service
  template:
    src: "startpantheon.j2"
    dest: "~/lacchain/start-pantheon.sh"
    mode: 0775
    force: yes

- name: Generate Pantheon configuration file
  template:
    src: "pantheon-config.j2"
    dest: "~/lacchain/config.toml"
    mode: 0775

- name: Copy service file to systemd
  copy:
    src: "{{ role_path }}/files/pantheon.service"
    dest: /lib/systemd/system/pantheon.service
    mode: 0775

- name: Copy Log configuration file to lacchain
  copy:
    src: "{{ role_path }}/files/log.xml"
    dest: "~/lacchain/log.xml"
    mode: 0775

- name: Enable service pantheon
  service:
    name: pantheon
    enabled: yes
