---
- name: Init pantheon
  debug:
        msg: "Init Pantheon"

- name: create lacchain directories
  file:
        path: "{{ item.dest }}"
        mode: "{{ item.mode }}"
        state: directory
  with_items:
        - { dest: "~/lacchain/data", mode: "0440" }
        - { dest: "~/lacchain/logs", mode: "0440" }
        - { dest: "~/lacchain/tmp", mode: "0440" }

- name: initializing pantheon from genesis.json
  debug:
        msg: Initializing Pantheon

- name: Copy genesis ibft2.0 file
  copy:
        src: "{{ role_path }}/files/genesis.json"
        dest: ~/lacchain/data/genesis.json
        mode: 0755

- name: Copy node key to first bootnode node
  copy:
        src: "{{ role_path }}/files/key"
        dest: ~/lacchain/data/key
        mode: 0700
  when: first_node

- name: Copy bootnode key to first bootnode node
  copy:
        src: "{{ role_path }}/files/bootnode"
        dest: ~/lacchain/data/bootnode
        mode: 0700
  when: first_node

- name: Generate node key
  shell: pantheon --genesis-file=/root/lacchain/data/genesis.json --data-path=/root/lacchain/data public-key export --to=/root/lacchain/data/bootnode | grep -oE "0x[A-Fa-f0-9]*" | sed 's/0x//'
  register: enode_key
  when: bootnode

- name: print enode key
  debug:
        msg: enode://{{enode_key.stdout}}@{{node_ip}}:60606
  when: bootnode

- name: Copy bootnodes variable from validators
  copy:
        src: "{{ playbook_dir }}/roles/lacchain-validator-node/vars/main.yml"
        dest: ~/lacchain/tmp/main.yml
        mode: 0700
  when: bootnode

- name: update bootnodes connection
  replace:
        dest: ~/lacchain/tmp/main.yml
        regexp: '60606"$'
        replace: "60606,"
  when: bootnode

- name: add new bootnode to running validator or writer
  replace:
        dest: ~/lacchain/tmp/main.yml
        regexp: "60606,$"
        replace: ',"enode://{{enode_key.stdout}}@{{node_ip}}:60606"]'
  when: bootnode

- name: Generate shell script to execute geth service
  template:
        src: "startpantheon.j2"
        dest: "~/lacchain/start-pantheon.sh"
        mode: 0775
        force: yes

- name: Generate Pantheon configuration file
  template:
    src: "pantheon-config.j2"
    dest: "~/lacchain/config.toml"
    mode: 0775

- name: Copy service file to systemd
  copy:
        src: "{{ role_path }}/files/pantheon.service"
        dest: /lib/systemd/system/pantheon.service
        mode: 0775

- name: Copy Log configuration file to lacchain
  copy:
        src: "{{ role_path }}/files/log.xml"
        dest: "~/lacchain/log.xml"
        mode: 0775

- name: Enable service pantheon
  service:
        name: pantheon
        enabled: yes
